# Generated by Django 4.1.2 on 2022-11-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('area', models.CharField(max_length=50)),
                ('legajo', models.IntegerField()),
                ('contacto', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('date', models.DateField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='post')),
            ],
        ),
    ]
